# Generated by Django 5.2 on 2025-04-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attariq', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_year')},
        ),
    ]
